buildscript {
    repositories {
        jcenter()
        maven {
            name = "forge"
            url = "http://maven.minecraftforge.net"
        }
        maven {
            name = "jitpack"
            url = "https://jitpack.io/"
        }
    }
    dependencies {
        classpath "com.github.asbyth:ForgeGradle:6f53277"
    }
}
plugins {

    id 'org.jetbrains.kotlin.jvm'
}
apply plugin: 'net.minecraftforge.gradle.tweaker-client'


version = "1.0"
group= "com.yourname.modid" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = "modid"

minecraft {
    version = "1.8.9"
    runDir = "run"
    tweakClass = "net.melonclient.minecraft189.tweaker.Minecraft189TweakerKt"
    mappings = "stable_22"
}

dependencies {
    implementation(project(":minecraft-api"))
    implementation(project(":common"))
    implementation 'com.github.Hippo:LWJEB:5.0.1'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}
